import { supabase } from '@/integrations/supabase/client';

export const removeBackground = async (file: File, type: 'CLOTHING' | 'PERSON' = 'CLOTHING'): Promise<string> => {
    try {
        // Convert file to base64 data URL for the edge function
        const base64 = await new Promise<string>((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(file);
        });

        const { data, error } = await supabase.functions.invoke('remove-background', {
            body: { imageUrl: base64 },
        });

        if (error) {
            console.error('Edge function remove-background error:', error);
            throw new Error(`Edge function error: ${error.message}`);
        }

        if (data?.processedImageUrl) {
            if (data.fallback) {
                console.warn('Background removal fallback:', data.error);
            }
            return data.processedImageUrl;
        }

        throw new Error("No image generated by background removal");
    } catch (error) {
        console.error("Background removal failed", error);
        throw error;
    }
};
