
export const removeBackground = async (file: File, type: 'CLOTHING' | 'PERSON' = 'CLOTHING'): Promise<string> => {
    try {
        const formData = new FormData();
        formData.append('file', file);
        formData.append('type', type);

        const backendUrl = import.meta.env.VITE_BACKEND_URL || 'http://localhost:3011';
        const response = await fetch(`${backendUrl}/api/remove-background`, {
            method: 'POST',
            body: formData,
        });

        if (!response.ok) {
            throw new Error(`Backend error: ${response.statusText}`);
        }

        const data = await response.json();
        if (data.result) {
            return data.result; // This is a base64 string
        }

        throw new Error("No image generated by background removal");
    } catch (error) {
        console.error("Background removal failed", error);
        throw error;
    }
};
