import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { GoogleGenAI } from "npm:@google/genai";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { personImageUrl, clothingItems } = await req.json();

    if (!personImageUrl || !clothingItems || clothingItems.length === 0) {
      throw new Error('Person image and at least one clothing item are required');
    }

    const GEMINI_API_KEY = Deno.env.get('GOOGLE_GEMINI_API_KEY') || Deno.env.get('GEMINI_API_KEY');
    if (!GEMINI_API_KEY) {
      throw new Error('GOOGLE_GEMINI_API_KEY is not configured');
    }

    console.log('Creating outfit try-on with', clothingItems.length, 'items utilizing Google GenAI recontextImage API');

    // Fetch person image as base64
    const { base64: personImageBase64 } = await fetchImageAsBase64WithMime(personImageUrl);

    // Fetch all clothing images as base64
    const productImagesPromises = clothingItems.map(async (item: any) => {
      if (item.image_url) {
        const { base64 } = await fetchImageAsBase64WithMime(item.image_url);
        return {
          productImage: {
            bytesBase64Encoded: base64
          }
        };
      }
      return null;
    });

    const productImages = (await Promise.all(productImagesPromises)).filter(Boolean);

    if (productImages.length === 0) {
      throw new Error("No valid clothing images provided");
    }

    const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
    
    // Virtual Try-on API Endpoint
    const response = await ai.models.recontextImage({
      model: 'imagen-product-recontext-preview-06-30',
      source: {
        personImage: {
          bytesBase64Encoded: personImageBase64
        },
        productImages: productImages
      },
      config: {
        numberOfImages: 1,
        safetyFilterLevel: 'BLOCK_MEDIUM_AND_ABOVE',
        personGeneration: 'ALLOW_ADULT' 
      }
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const generatedImage = response.generatedImages[0];
      if (generatedImage.bytesBase64Encoded) {
        const tryOnImageUrl = `data:image/png;base64,${generatedImage.bytesBase64Encoded}`;
        console.log('Outfit try-on completed successfully');
        return new Response(
          JSON.stringify({ tryOnImageUrl }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
    }

    throw new Error('No try-on image generated by Google (Empty payload)');
  } catch (error) {
    console.error('Error in outfit try-on:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});

async function fetchImageAsBase64WithMime(url: string): Promise<{ base64: string; mimeType: string }> {
  if (url.startsWith('data:')) {
    const matches = url.match(/^data:([^;]+);base64,(.+)$/);
    if (matches) {
      return { mimeType: matches[1], base64: matches[2] };
    }
    return { mimeType: 'image/jpeg', base64: url.split(',')[1] };
  }

  const response = await fetch(url);
  const contentType = response.headers.get('content-type') || 'image/jpeg';
  const mimeType = contentType.split(';')[0];
  const arrayBuffer = await response.arrayBuffer();

  const bytes = new Uint8Array(arrayBuffer);
  let binary = '';
  const chunk_size = 8192;
  for (let i = 0; i < bytes.length; i += chunk_size) {
    binary += String.fromCharCode.apply(null, Array.from(bytes.subarray(i, i + chunk_size)));
  }
  const base64 = btoa(binary);
  return { base64, mimeType };
}
