[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm ci",
  "python3 -m venv python/.venv",
  "python/.venv/bin/pip install rembg[cpu] pillow pillow-heif"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/server.js"
